[workspace]
members = [
    "firmware",
    "host_tools",
    "protocol",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"

[profile.dev]
panic = "abort"
overflow-checks = true

[profile.release]
panic = "abort"
codegen-units = 1
lto = "fat"
overflow-checks = true
strip = "symbols"

[workspace.lints.rust]
rust_2018_idioms = "deny"
unused_must_use = "deny"

[workspace.lints.clippy]
dbg_macro = "deny"
expect_used = "deny"
panic = "deny"
todo = "deny"
unimplemented = "deny"
unwrap_used = "deny"
