[package]
name = "rp_hsm"
version.workspace = true
edition.workspace = true

[dependencies]
chacha20poly1305 = { version = "0.10.1", default-features = false }
ed25519-dalek = { version = "2.1.1", default-features = false, features = ["zeroize"] }
heapless = "0.8.0"
p256 = { version = "0.13.2", default-features = false, features = ["ecdsa"] }
rand_chacha = { version = "0.3.1", default-features = false }
rand_core = { version = "0.6.4", default-features = false }

[lints]
workspace = true
