[alias]
firmware-build = "build -p firmware --target riscv32imac-unknown-none-elf"
firmware-run = "run -p firmware --target riscv32imac-unknown-none-elf"
firmware-run-developer = "run -p firmware --target riscv32imac-unknown-none-elf --features developer-mode"
probe = "run -p host_tools --bin probe_protocol"
rphsmtool = "run -p host_tools --bin rphsmtool --"

[target.riscv32imac-unknown-none-elf]
rustflags = [
    "-C", "link-arg=--nmagic",
    "-C", "link-arg=-Trp235x_riscv.x",
    "-C", "link-arg=-Tdefmt.x",
]
runner = "picotool load -u -v -x -t elf"
